### ISSUE TITLE
The hyperlink to AI4Animation dataset is broken again

### ISSUE THREAD

**Issue by Bin-Ji** [Georgedf1/AnimationResearchUtils#1]
Hi George
The link for NSM(2019) dataset is broken again. I noticed that you encountered a similar issue recently. I have already created a new issue in AI4Aniatmion, but there is no reply yet. Can you provide an alternative source where I can obtain this dataset?  Your assistance is greatly appreciated.

**Comment by georgedf1** [comment]
Not aware of an alternate source for the NSM dataset specifically, so you're probably going to have to wait or reach out the paper authors directly by email.

**Comment by Bin-Ji** [comment]
Thank you for your reply.

**Comment by georgedf1** [comment]
Looks like they fixed it!
